version: "3.9"
services:
  db:
    image: postgres
    ports: -5432:5432
    volumes:
      -
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
  app:
    image: my-node-app
    build: .
    command: npm run dev
    ports:
      - 3000:3000
